### ISSUE TITLE
May function '_encode_split' raises exception?

### ISSUE THREAD

**Issue by zw-ruan** [gofer/libbase64#2]
In the function:
```cpp
	std::string _encode_split(std::string in) {
 		char _out[5];
		_out[0] = Base64Table.at((in[0] & 0xFC) >> 2);
		_out[1] = Base64Table.at((in[0] & 0x03) << 4 | (in[1] & 0xF0) >> 4);
		_out[2] = Base64Table.at((in[1] & 0x0F) << 2 | (in[2] & 0xC0) >> 6);
		_out[3] = Base64Table.at((in[2] & 0x3F));
		_out[4] = '\0';
		return std::string(_out);
	}
```
when the `in`'s size is 1. `in[2]` may raise exception? According to the http://www.cplusplus.com/reference/string/string/operator[]/, when the index is larger than the string length,  it causes undefined behavior..

**Comment by gofer** [comment]
As you pointed out, this function may cause exceptions.
I modified `base64_encode.cpp` and `base64_decode.cpp` at commit 84d32fc.
